exports.namePlanes = [
    { x: 55, z: -695, imageUrl: 'assets/places/vecmilgravis' },
    { x: 140, z: 577, imageUrl: 'assets/places/andrejsala' },
    { x: 160, z: -172, imageUrl: 'assets/places/kundzinsala' },
    { x: -123, z: -439, imageUrl: 'assets/places/krievusala' },
    { x: 364, z: -356, imageUrl: 'assets/places/mangali' },
    { x: 322, z: 148, imageUrl: 'assets/places/sarkandaugava' },
    { x: -314, z: -1096, imageUrl: 'assets/places/mangalsala' },
    { x: -439, z: -479, imageUrl: 'assets/places/bolderaja' },
    { x: -711, z: -732, imageUrl: 'assets/places/daugavgriva' },
    { x: -86, z: 770, imageUrl: 'assets/places/kipsala' },
    { x: -383, z: -732, imageUrl: 'assets/places/milestibas_salina' },
    { x: -166, z: 483, imageUrl: 'assets/places/spilve' },
    { x: -114, z: -262, imageUrl: 'assets/places/voleri' },
]